spring:
  datasource:
    url: "jdbc:mysql://rds-hostname:3306/starterpack?useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=utf8"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: never