------------------------------------------------------------
-- H2 DEV SCHEMA (in-memory)
-- 핵심: FK 동작 동일화
--  - pack_product.product_id → product.id : ON DELETE CASCADE
--  - pack_product.pack_id    → pack.id    : ON DELETE CASCADE
--  - product.category_id     → category.id: ON DELETE SET NULL
--  - pack.category_id        → category.id: ON DELETE SET NULL
------------------------------------------------------------

-- 깨끗이 비우고 시작 (순서 중요: 자식 → 부모)
DROP TABLE IF EXISTS feed_bookmark;
DROP TABLE IF EXISTS feed_like;
DROP TABLE IF EXISTS pack_like;
DROP TABLE IF EXISTS pack_bookmark;
DROP TABLE IF EXISTS pack_product;
DROP TABLE IF EXISTS feed;
DROP TABLE IF EXISTS pack;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS link_policy;
DROP TABLE IF EXISTS member;

------------------------------------------------------------
-- 1) 멤버
------------------------------------------------------------
CREATE TABLE member (
  user_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email              VARCHAR(100) NOT NULL,
  password           VARCHAR(255),
  name               VARCHAR(50)  NOT NULL,
  nickname           VARCHAR(50)  NOT NULL,
  provider           VARCHAR(20),
  provider_id        VARCHAR(100),
  profile_image_url  VARCHAR(500),
  is_active          BOOLEAN      NOT NULL DEFAULT TRUE,
  role               VARCHAR(20)  NOT NULL DEFAULT 'USER',
  birth_date         DATE,
  gender             VARCHAR(10),
  phone_number       VARCHAR(20),
  refresh_token      VARCHAR(500),
  created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_member_role CHECK (role IN ('USER','ADMIN')), -- (선택) Enum 보호
  CONSTRAINT chk_member_gender CHECK (gender IN ('MALE', 'FEMALE'))
);

CREATE UNIQUE INDEX uk_member_email       ON member(email);
CREATE UNIQUE INDEX uk_member_nickname    ON member(nickname);
CREATE UNIQUE INDEX uk_member_provider_id ON member(provider, provider_id);
CREATE INDEX        idx_member_provider   ON member(provider);
CREATE INDEX        idx_member_is_active  ON member(is_active);

------------------------------------------------------------
-- 2) 카테고리
------------------------------------------------------------
CREATE TABLE category (
  id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name  VARCHAR(100) NOT NULL,
  src   VARCHAR(500)
);

CREATE UNIQUE INDEX uk_category_name ON category(name);

------------------------------------------------------------
-- 3) 상품
------------------------------------------------------------
CREATE TABLE product (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR(200) NOT NULL,
  link         VARCHAR(500),
  product_type VARCHAR(50),
  src          VARCHAR(500),
  cost         INT,
  like_count   INT NOT NULL DEFAULT 0,
  category_id  BIGINT
);

CREATE INDEX idx_product_name      ON product(name);
CREATE INDEX idx_product_category  ON product(category_id);
CREATE INDEX idx_product_like      ON product(like_count);

ALTER TABLE product ADD CONSTRAINT chk_product_cost_nonneg CHECK (cost IS NULL OR cost >= 0);
ALTER TABLE product ADD CONSTRAINT chk_product_like_nonneg CHECK (like_count >= 0);

ALTER TABLE product
  ADD CONSTRAINT fk_product_category
  FOREIGN KEY (category_id)
  REFERENCES category(id)
  ON DELETE SET NULL
  ON UPDATE CASCADE;

------------------------------------------------------------
-- 3) 링크 정책 (Blacklist)
------------------------------------------------------------
CREATE TABLE link_policy (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pattern     VARCHAR(500) NOT NULL,
  description VARCHAR(1000),
  created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

------------------------------------------------------------
-- 4) 스타터팩
------------------------------------------------------------
CREATE TABLE pack (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name             VARCHAR(100) NOT NULL,
  category_id      BIGINT,
  total_cost       INT,
  pack_like_count  INT NOT NULL DEFAULT 0,
  pack_bookmark_count INT NOT NULL DEFAULT 0,
  src              VARCHAR(500),
  description      CLOB
);

CREATE INDEX idx_pack_category ON pack(category_id);
CREATE INDEX idx_pack_like     ON pack(pack_like_count);
CREATE INDEX idx_pack_bookmark ON pack(pack_bookmark_count);

ALTER TABLE pack ADD CONSTRAINT chk_pack_total_cost_nonneg CHECK (total_cost IS NULL OR total_cost >= 0);
ALTER TABLE pack ADD CONSTRAINT chk_pack_like_nonneg       CHECK (pack_like_count >= 0);
ALTER TABLE pack ADD CONSTRAINT chk_pack_bookmark_nonneg   CHECK (pack_bookmark_count >= 0);

ALTER TABLE pack
  ADD CONSTRAINT fk_pack_category
  FOREIGN KEY (category_id)
  REFERENCES category(id)
  ON DELETE SET NULL
  ON UPDATE CASCADE;

------------------------------------------------------------
-- 5) 매핑 테이블: pack_product (복합 PK)
------------------------------------------------------------
CREATE TABLE pack_product (
  pack_id    BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  PRIMARY KEY (pack_id, product_id)
);

CREATE INDEX idx_pp_product ON pack_product(product_id);

ALTER TABLE pack_product
  ADD CONSTRAINT fk_pp_pack
  FOREIGN KEY (pack_id)
  REFERENCES pack(id)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE pack_product
  ADD CONSTRAINT fk_pp_product
  FOREIGN KEY (product_id)
  REFERENCES product(id)
  ON DELETE CASCADE
  ON UPDATE CASCADE;
------------------------------------------------------------
-- 6) 사용자 피드
------------------------------------------------------------
CREATE TABLE feed (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT       NOT NULL,
  description CLOB,
  image_url   VARCHAR(500) NOT NULL,
  category_id BIGINT,
  like_count  BIGINT       NOT NULL DEFAULT 0,
  bookmark_count  BIGINT   NOT NULL DEFAULT 0,
  created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 인덱스 추가
CREATE INDEX idx_feed_user     ON feed(user_id);
CREATE INDEX idx_feed_category ON feed(category_id);
CREATE INDEX idx_feed_like_count     ON feed(like_count);
CREATE INDEX idx_feed_bookmark_count ON feed(bookmark_count);

-- 제약 조건 추가
ALTER TABLE feed ADD CONSTRAINT chk_feed_like_count CHECK (like_count >= 0);
ALTER TABLE feed ADD CONSTRAINT chk_feed_bookmark_count CHECK (bookmark_count >= 0);

-- 외래 키(FK) 추가
ALTER TABLE feed
    ADD CONSTRAINT fk_feed_user
        FOREIGN KEY (user_id)
            REFERENCES member(user_id)
            ON DELETE CASCADE
            ON UPDATE CASCADE;

ALTER TABLE feed
    ADD CONSTRAINT fk_feed_category
        FOREIGN KEY (category_id)
            REFERENCES category(id)
            ON DELETE SET NULL
            ON UPDATE CASCADE;
------------------------------------------------------------
-- 8) 피드 좋아요
------------------------------------------------------------
CREATE TABLE feed_like (
   id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   feed_id     BIGINT    NOT NULL,
   member_id   BIGINT    NOT NULL,
   created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 유니크 및 인덱스 추가
CREATE UNIQUE INDEX uk_feed_like_member ON feed_like(feed_id, member_id);
CREATE INDEX idx_fl_member             ON feed_like(member_id);

-- 외래 키(FK) 추가
ALTER TABLE feed_like
    ADD CONSTRAINT fk_fl_feed
        FOREIGN KEY (feed_id)
            REFERENCES feed(id)
            ON DELETE CASCADE
            ON UPDATE CASCADE;

ALTER TABLE feed_like
    ADD CONSTRAINT fk_fl_member
        FOREIGN KEY (member_id)
            REFERENCES member(user_id)
            ON DELETE CASCADE
            ON UPDATE CASCADE;
------------------------------------------------------------
-- 9) 피드 북마크 (feed_bookmark)
------------------------------------------------------------
CREATE TABLE feed_bookmark (
   id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   feed_id     BIGINT    NOT NULL,
   member_id   BIGINT    NOT NULL,
   created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_feed_bookmark_member ON feed_bookmark(feed_id, member_id);
CREATE INDEX idx_fb_member                 ON feed_bookmark(member_id);

ALTER TABLE feed_bookmark
    ADD CONSTRAINT fk_fb_feed
        FOREIGN KEY (feed_id)
            REFERENCES feed(id)
            ON DELETE CASCADE
            ON UPDATE CASCADE;

ALTER TABLE feed_bookmark
    ADD CONSTRAINT fk_fb_member
        FOREIGN KEY (member_id)
            REFERENCES member(user_id)
            ON DELETE CASCADE
            ON UPDATE CASCADE;
------------------------------------------------------------
-- 10) 스타터팩 좋아요 (pack_like)
------------------------------------------------------------
CREATE TABLE pack_like (
   id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   pack_id     BIGINT    NOT NULL,
   member_id   BIGINT    NOT NULL,
   created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_pack_like_member ON pack_like(pack_id, member_id);
CREATE INDEX idx_pl_member             ON pack_like(member_id);

ALTER TABLE pack_like
    ADD CONSTRAINT fk_pl_pack
        FOREIGN KEY (pack_id)
            REFERENCES pack(id)
            ON DELETE CASCADE
            ON UPDATE CASCADE;

ALTER TABLE pack_like
    ADD CONSTRAINT fk_pl_member
        FOREIGN KEY (member_id)
            REFERENCES member(user_id)
            ON DELETE CASCADE
            ON UPDATE CASCADE;
------------------------------------------------------------
-- 11) 스타터팩 북마크 (pack_bookmark)
------------------------------------------------------------
CREATE TABLE pack_bookmark (
   id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   pack_id     BIGINT    NOT NULL,
   member_id   BIGINT    NOT NULL,
   created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_pack_bookmark_member ON pack_bookmark(pack_id, member_id);
CREATE INDEX idx_pb_member                 ON pack_bookmark(member_id);

ALTER TABLE pack_bookmark
    ADD CONSTRAINT fk_pb_pack
        FOREIGN KEY (pack_id)
            REFERENCES pack(id)
            ON DELETE CASCADE
            ON UPDATE CASCADE;

ALTER TABLE pack_bookmark
    ADD CONSTRAINT fk_pb_member
        FOREIGN KEY (member_id)
            REFERENCES member(user_id)
            ON DELETE CASCADE
            ON UPDATE CASCADE;
